# CA3 Capstone Project - Predicting Food Waste with Machine Learning
Dataset: Food Waste Recycling Impact - Town of Cary
https://data.townofcary.org/explore/dataset/food-waste-pilot/

In [1]:
# I used this code to import the libraries I need for data analysis and charts
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
# I used this code to load the dataset and see the first 5 rows
df = pd.read_csv('food-waste-pilot.csv')
df.head()

,Stop Name,Collection Date,Food Waste Collected,Estimated Earned Compost Created
0,Citizen's Convenience Center,2026-04-29,515.8,52.0
1,Mills Park,2026-04-29,537.0,54.0
2,Mills Park,2026-04-27,561.0,56.0
3,Citizen's Convenience Center,2026-04-27,1093.0,109.0
4,Citizen's Convenience Center,2026-04-24,641.6,64.0

In [3]:
# I used this code to check the size of the dataset (rows, columns)
df.shape

(1006, 4)

i saw, the dataset has 1006 rows and 4 columns.

In [4]:
# I used this code to check the data type of each column and see if there are empty values
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1006 entries, 0 to 1005
Data columns (total 4 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Stop Name                         1006 non-null   str
 1   Collection Date                   1006 non-null   str
 2   Food Waste Collected              1006 non-null   float64
 3   Estimated Earned Compost Created  1006 non-null   float64
dtypes: float64(2), str(2)
memory usage: 62.7 KB

In [5]:
# I used this code to see the main statistics of the numeric columns
df.describe()

       Food Waste Collected  Estimated Earned Compost Created
count           1006.000000                       1006.000000
mean             644.130219                         64.382704
std              307.244105                         30.726067
min                0.000000                          0.000000
25%              452.900000                         45.000000
50%              598.400000                         60.000000
75%              762.975000                         76.000000
max             2057.000000                        206.000000

i can see, the average food waste per collection is about 644 lbs. The minimum is 0 lbs, which may mean the site was closed that day, and the maximum is about 2,057 lbs, which may be an outlier.

In [6]:
# I used this code to see how many collections each drop-off site has
df['Stop Name'].value_counts()

Stop Name
Citizen's Convenience Center    656
Mills Park                      350
Name: count, dtype: int64

As we can see, there are 2 sites: Citizen's Convenience Center (656 collections) and Mills Park (350 collections). Our target is Food Waste Collected.